FROM nvidia/cuda:11.7.0-base-ubuntu20.04

ENV PYTHON_VERSION=3.9

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq update \
    && apt-get -qq install --no-install-recommends \
    python${PYTHON_VERSION} \
    python3-pip \
    sox \
    libsox-fmt-all \
    libsox-fmt-mp3 \
    ffmpeg && rm -rf /var/lib/apt/lists/*


RUN ln -s -f /usr/bin/python${PYTHON_VERSION} /usr/bin/python3 && \
    ln -s -f /usr/bin/python${PYTHON_VERSION} /usr/bin/python && \
    ln -s -f /usr/bin/pip3 /usr/bin/pip

RUN pip3 install torch==1.13.0+cu117 -f https://download.pytorch.org/whl/torch


RUN pip3 install openai-whisper
RUN pip3 install sox
RUN pip3 install numpy
RUN pip3 install python-dotenv
RUN pip3 install requests
RUN pip3 install coloredlogs
RUN pip3 install pika

COPY /app /app


ENTRYPOINT ["python", "app/main.py"]
